name: L'intégration continue
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-ui:
    name: Construction de l'interface utilisateurice de MesQuestionsCyber
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@v4

      - name: Déterminer la version de Node.js à utiliser
        run: |
          echo "NODE_VERSION=$(./scripts/get-node-version.sh)" >> $GITHUB_ENV

      - name: Utiliser la version Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Installer les dépendances
        run: npm install -g "$(jq -r '.packageManager' package.json)" && pnpm install
        working-directory: ui

      - name: Contrôler les types
        run: npm run check
        working-directory: ui

      - name: Contrôler le linting
        run: npm run lint:check
        working-directory: ui

      - name: Contrôler la mise en forme
        run: npm run format:check
        working-directory: ui

  build:
    name: Construction de MesQuestionsCyber
    runs-on: ubuntu-latest

    env:
      ALBERT_API_KEY: une-fausse-clef
      COLLECTION_ID_ANSSI_LAB: 42
      MODE: test

    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Installer uv
        uses: astral-sh/setup-uv@v6

      - name: Installer les dépendances
        run: uv sync

      - name: Contrôler le format du code
        run: uv run ruff check

      - name: Contrôler les types
        run: uv run mypy

      - name: Exécuter les tests
        run: uv run pytest
